language: go
go:
  - "1.12"

env:
  - GO111MODULE=on

install: true

jobs:
  include:
    - stage: check with linter
      before_script:
        - ./linter.sh install
      script:
        - make lint
    - stage: run tests
      script:
        - make test
    - stage: build image
      script:
        - make build_image
      after_success:
        - if [[ "${TRAVIS_BRANCH}" = "master" ]] && [[ "${TRAVIS_PULL_REQUEST}" = "false" ]]; then
          make push_image;
          fi
